### PR TITLE
updated population

### PR DESCRIPTION
**Pull request by isunix11**
updated population

### CODE REVIEW

**Comment by thepassle** [comment]
oh i just pushed these changes just now

**Comment by thepassle** [comment]
I would've preferred a MR for the implementation on this 😅, there seems to be a lot of data in the json file that we dont need, and currently the whole json file is requested each time. It should be enough to request the file only once, keep it in memory, and when a next dialog is opened, just get the iso2 key from the cached object. That saves the users a lot of data usage

**Comment by isunix11** [comment]
Sure, I will update

**Comment by thepassle** [comment]
continued here https://github.com/Code-for-All/lockdown/pull/115

**Pull request closed without merging**
