### PR TITLE
Processed the list by @ilyasfoo

### PR DESCRIPTION
**Pull request by milovanderlinden**
Please review

### CODE REVIEW

**Comment by thepassle** [comment]
So these should be added to base.json instead right?  This is what was discussed on slack? To avoid the worldmap being overwritten again

**Comment by ilyasfoo** [comment]
@milovanderlinden the file should be at https://github.com/Code-for-All/lockdown/blob/master/backend/src/loaders/worldmap/base.json. Otherwise your changes will be overwritten

**Comment by LarsDenBakker** [comment]
@ilyasfoo There are still conflicts :(

**Comment by ilyasfoo** [comment]
I can't seem to find the conflict, I've even tried to merge into a fresh cloned master branch without issues. Can help highlight where do you find it @LarsDenBakker ?

**Comment by LarsDenBakker** [comment]
Git said there are conflicts, but it doesnt anymore now.

**Pull request merged**
