### PR TITLE
Update datafile to new structure reflecting google sheets

### PR DESCRIPTION
**Pull request by ilyasfoo**
Please review the new structure, the data is dummied for all territories, from [the demo sheet](https://docs.google.com/spreadsheets/d/1mVyQxxLxAF3E1dw870WHXTOLgYzmumojvzIekpgvLV0/edit#gid=1042330907)

Linted version: http://myjson.com/q9l6w

Note: 
- Limit to first 10 territories temporarily to approve the structure
- Only the first entry is obtained for now.

### CODE REVIEW

**Comment by thepassle** [comment]
This is looking great 🙂 

Instead of having object keys for measures etc, could we do something like this?

```js
{
  "DZ":{
    "lockdowns":{
      "status":"Ready",
      "measures": [
        {
          "label": "max_gatherings",
          "value": 2,
          "start":"",
          "end":""
        },
        {
          "label": "self_isolation",
          "value": true,
          "start":"",
          "end":""
        }
        // etc
      ],
      "travel": {
        "land": [
          {
            "label": "local",
            "value": true,
            "start": "",
            "end":""
          },  
          {
            "label": "national_inbound",
            "value": true,
            "start": "",
            "end":""
          }
          //etc
        ],
        "flight": [/*etc*/],
        "sea": [/*etc*/]
      }
    }
  }
}

```

We could then access the data on the frontend a bit easier like `countries['DZ'].lockdowns.measures`, `countries['DZ'].lockdowns.travel.flight`

and iterate over them like

```js
countries['DZ'].lockdowns.measures.map(measure => html`${measure.label}: ${measure.value}`)
```

**Comment by ilyasfoo** [comment]
Good idea, will do this soonest

**Comment by ilyasfoo** [comment]
I have reworked the structure and included all data in the territory tab now. Here's a [preview](https://jsonblob.com/9d1121d4-7196-11ea-9a7f-53e524868408)

Unfortunately, the data size grew to 1.7MB so far, as per demo there's 249 territories and 5 entries each.

Now I'm thinking we might need to minimize the general data, and only fetch required data on user action, which depends on the presentation layer.

Let me know @thepassle

**Comment by thepassle** [comment]
This is looking good! I have a few small comments, and one general remark:

## General comment

What we need is two different types of json files

- One 'global' json file to render the world map, in this file a country would only need an identifier (name/iso code?), and the state of lockdown. We need this to display the color of a country on the world map

- Then we need separate json files per country. So instead of having one big file with all the countries in it, we can have `/data/en.json`, `/data/nl.json`, that have the specific country data (max gathering, travel info etc). So the structure you have here is fine, but they should be separate files per country, so we can lazily request them from the frontend, instead of hogging the users data by download one big 1.7mb json file.

Does that make sense? Please let me know if not, I can try to explain better, or we can hop on a quick call 🙂 

## Schema comments

There's a mistake in the max gatherings, 'start' should be a date, I think it should be `"value": 1000`, and it should be a number instead of a string

```js
            {
              "label": "max_gathering",
              "start": "1000"
            },
```

Yes/no values should be booleans:
```diff
-              "value": "No"
-              "value": "Yes"
+              "value": false
+              "value": true
```

If we dont have data for a label, can we have null as value? e.g.:

```js
              {
                "label": "cross_border_workers",
                "value": null,
              },
```

**Comment by ilyasfoo** [comment]
Thanks! Sorry, couldn't find time to have a call for now. Couple of points to discuss:

> ## General comment
> * One 'global' json file to render the world map, in this file a country would only need an identifier (name/iso code?), and the state of lockdown. We need this to display the color of a country on the world map

"State of lockdown" is actually tricky because it also depends on the current date which will require some backend execution to figure out. We have 2 choices:
- Generate data for every date possible, so queries will be 
like `/data/2020-04-01/territories/nl.json` etc. I feel this is still feasible given our situation, just a little instability (non-generated dates will be 404). Also I think our end goal is to have time-based data too right?
- Backend gives all states for a particular territory `/data/territories/nl.json`, frontend will have to do the hard work to figure which lockdown state is the current.

> ## Schema comment
> Yes/no values should be booleans:
> 
> ```diff
> -              "value": "No"
> -              "value": "Yes"
> +              "value": false
> +              "value": true
> ```
Actually there's 4 possible values for most of these values as per following example:

image

Please let me know if you need to simplify. Important is to clear the logic with the rest of the team so I don't make any mistakes when transforming data.

Noted on the other feedbacks, thanks!

**Comment by thepassle** [comment]
> Actually there's 4 possible values for most of these values as per following example:

Ah okay, I see. That makes sense, keep it as is then, we'll have to map it on the frontend, thats fine

> "State of lockdown" is actually tricky because it also depends on the current date which will require some backend execution to figure out. We have 2 choices:

For the MVP we will only show the current status per country, so we dont have to worry about dates. The google sheets should have a current lockdown status per country. No need to worry about dates for now. If theres no field for that in the google sheets, it should be added there

**Comment by ilyasfoo** [comment]
Sorry, deleted my comment because just had the idea to actually have the generated dates & also current as per script run. Nevermind that.

> For the MVP we will only show the current status per country, so we dont have to worry about dates. The google sheets should have a current lockdown status per country. No need to worry about dates for now. If theres no field for that in the google sheets, it should be added there

Yes currently thats not available yet, should I ping Jean?

My old comment for reference:
> Thanks! Sorry, couldn't find time to have a call for now. Couple of points to discuss:
> 
> > ## General comment
> > * One 'global' json file to render the world map, in this file a country would only need an identifier (name/iso code?), and the state of lockdown. We need this to display the color of a country on the world map
> 
> "State of lockdown" is actually tricky because it also depends on the current date which will require some backend execution to figure out. We have 2 choices:
> - Generate data for every date possible, so queries will be 
> like `/data/2020-04-01/territories/nl.json` etc. I feel this is still feasible given our situation, just a little instability (non-generated dates will be 404). Also I think our end goal is to have time-based data too right?
> - Backend gives all states for a particular territory `/data/territories/nl.json`, frontend will have to do the hard work to figure which lockdown state is the current.
> 
> > ## Schema comment
> > Yes/no values should be booleans:
> > 
> > ```diff
> > -              "value": "No"
> > -              "value": "Yes"
> > +              "value": false
> > +              "value": true
> > ```
> Actually there's 4 possible values for most of these values as per following example:
> 
> image
> 
> Please let me know if you'd like a simplified value instead. Important is to clear the logic with the rest of the team so I don't make any mistakes when transforming data.
> 
> Noted on the other feedbacks, thanks!

**Comment by thepassle** [comment]
> Yes currently thats not available yet, should I ping Jean?

Yeah thatd be great 🙂

**Comment by LarsDenBakker** [comment]
Thanks a lot for your work on this, it helps a lot!

Regarding the non-binary states (yes/no/partial/unclear) shall we do an enum instead? YES / NO / PARTIAL / UNCLEAR

**Comment by ilyasfoo** [comment]
Glad i'm able to help 😁

> Regarding the non-binary states (yes/no/partial/unclear) shall we do an enum instead? YES / NO / PARTIAL / UNCLEAR

May I ask what does it help with particularly? Currently i'm allowing flexibility as Jean starts to insert data into the sheet, I assume changes are going to come soon too

**Comment by ilyasfoo** [comment]
@thepassle Please have a look at the updated data structure

**Comment by thepassle** [comment]
@ilyasfoo Looks great! 😄 

Is there any documentation on how to run the scripts/generate the files so we can automate them in the CI that lars worked on?

These data files are directly taken from the google sheets, right? So these are up to date, and we could already consume them in the frontend?

How are errors handled? E.g. can something change in the google sheets? Is everything aligned with jean so no breaking changes get made to the excel sheet and the script breaks down? etc

**Comment by LarsDenBakker** [comment]
@ilyasfoo It depends on what this field is intended for. If it's just a plain text field that we should show as is, then indeed it doesn't matter what's in there. If the field has some meaning, and modifies the UI in some way, the values need to be known upfront and be consistent. For instance it should not be a mix of upper and lower case.

There is where the backend script plays a crucial role, it needs to ensure the excel sheet doesn't input some strange values and crash the front-end.

**Comment by ilyasfoo** [comment]
@thepassle 

> Is there any documentation on how to run the scripts/generate the files so we can automate them in the CI that lars worked on?

This pretty much works on running, no other options required other than the google creds.

> These data files are directly taken from the google sheets, right? So these are up to date, and we could already consume them in the frontend?

Yes

> How are errors handled? E.g. can something change in the google sheets? Is everything aligned with jean so no breaking changes get made to the excel sheet and the script breaks down? etc

No proper error handling is set up yet, it'll just spew error on console. Will look into maybe slack integration & notify us if it breaks next. 

I've only told Jean that he'd needed to notify me if any changes occur in the sheet's grid. He's currently working on doing lookups from one place, will see what to do next from there on

**Comment by ilyasfoo** [comment]
> @ilyasfoo It depends on what this field is intended for. If it's just a plain text field that we should show as is, then indeed it doesn't matter what's in there. If the field has some meaning, and modifies the UI in some way, the values need to be known upfront and be consistent. For instance it should not be a mix of upper and lower case.
> There is where the backend script plays a crucial role, it needs to ensure the excel sheet doesn't input some strange values and crash the front-end.

I agree with that. Will set a couple of field definitions to standardize from

**Comment by ilyasfoo** [comment]
Data is now generated & commited by CI, closing this

**Pull request closed without merging**
