### PR TITLE
Feat/territories total

### PR DESCRIPTION
**Pull request by ilyasfoo**
Prerequisite PR: https://github.com/Code-for-All/lockdown/pull/137

Fixes https://github.com/Code-for-All/lockdown/issues/74. Changed both script and frontend

`totals.json`:
```json
{
  "corona": {
    "confirmed": 976249,
    "date": "2020-04-04T10:46:55+08:00",
    "deaths": 50489
  },
  "territories": {
    "lockdown": 0
  }
}
```

### CODE REVIEW

**Comment by LarsDenBakker** [comment]
@ilyasfoo I think this one will need to be rebased as well

**Comment by ilyasfoo** [comment]
Yes, will do in a minute

**Comment by ilyasfoo** [comment]
@LarsDenBakker ready for review, thanks!

**Comment by ilyasfoo** [comment]
Alright should be good to go

**Comment by thepassle** [comment]
@ilyasfoo Looking at: https://github.com/Code-for-All/lockdown/blob/master/data/totals.json I see that `lockdowns` is 249, does that mean 249 countries are in lockdown? Is that correct?

Also I dont see how many people are affected, or is that not implemented yet?

image

**Comment by ilyasfoo** [comment]
Yes @thepassle . People affected isn't implemented yet. The logic for deriving that value is still not given AFAIK

**Comment by thepassle** [comment]
Okay, gotcha 🙂 What about the number of lockdowns? `249`?

**Comment by ilyasfoo** [comment]
Correct. The sum is simply territories with lockdown_status value of `Partial` and `Yes`

**Comment by thepassle** [comment]
Okay great, just making sure. Wow thats a lot 😱 Nice work on these PRs, thanks!

**Comment by ilyasfoo** [comment]
No probs @thepassle . Btw please note the data is still dummied, its grabbing from `PLAYGROUND` sheet this time. Can't wait until editors get data in, hope that's soon since that's the block until our first release I think

**Comment by thepassle** [comment]
As I understood Jean the editors are already collecting data, maybe you can check with him, and already use the 'real' sheets?

**Pull request merged**
