### PR TITLE
WIP: backend/feat time-slider

### PR DESCRIPTION
**Pull request by ilyasfoo**
Snapshots are generated by lockdown loader.
Summary of snapshot data generated from lockdown loader will be used by worldmap & totals loader.

For now we should try produce all 10 week of data for each territory into individual, per-territory JSON files to take advantage of better compression.

Backend changes needed:
- [x] Snapshots generate range of 10 week data (previous 2 week, next 8 week)
- [x] Worldmap `lockdown_state` needs to support multiple dates
- [x] Totals for sum of lockdown needs to support multiple dates 
- [x] Produce start & end dates (maybe in `totals.json`?)
- [x] Exclude `null` datapoints altogether to save space

### CODE REVIEW

**Comment by LarsDenBakker** [comment]
Maybe we should slice it, we could do the backend change and the front-end just picks the current data from the data. Then the slider can be a separate PR. What do you think?

**Comment by ilyasfoo** [comment]
Yes that can too @LarsDenBakker

**Comment by ilyasfoo** [comment]
Anyone wants to pick up frontend? I assume tasks includes these:

Frontend changes needed:
- [ ] Timeslider UI
- [ ] Worldmap to support date selection
- [ ] Popup UI to support date selection
- [ ] Define default datapoints that assumes missing data from JSON as `no data`

**Comment by aherreDev** [comment]
@ilyasfoo I'm currently working on the Time Slider component

**Comment by aherreDev** [comment]
I can take all Front end tasks if You want

**Comment by ilyasfoo** [comment]
Great @aherreDev , can you make a new PR for frontend? This is for better focused discussions

**Comment by aherreDev** [comment]
@ilyasfoo I can't do a new PR for this branch because we only can have one active PR per branch

**Comment by aherreDev** [comment]
If you want I can make a new branch but I need to know what name I have to put in

**Comment by ilyasfoo** [comment]
@aherreDev u can use WIP: frontend/feat time-slider

**Comment by lchipres** [comment]
@ilyasfoo I will take snapshot generation

**Pull request merged**
