### PR TITLE
Add translation into Japanese [Internationalization]

### PR DESCRIPTION
**Pull request by kota-yata**
Sorry for sudden PR. 

I didn't translate title and other {Lockdown Project} as the other translation files.
If it's OK, I'd appreciate it if you could merge this PR.

### CODE REVIEW

**Review by aherreDev — APPROVED** [review]
Looks very nice!!, Thanks for all!

**Comment by aherreDev** [comment]
@MarkDatysgeld can you please confirm if we are able to add this language? The code it's good

**Comment by kota-yata** [comment]
Oh, this repository looks like being migrated. I will try to send the same PR to the next repository :)

**Comment by JFQueralt** [comment]
Hi @kota-yata 
Correct, we are migrating and starting the MAP from scratch.
We'll be enabling an easier way for people to help with translations. Would you like to help with Japanese?

**Comment by kota-yata** [comment]
Yes, I'm going to create Translation PR at the new repository

**Pull request closed without merging**
