### PR TITLE
Feat/backend worldmap

### PR DESCRIPTION
**Pull request by ilyasfoo**
Prerequisite PR: https://github.com/Code-for-All/lockdown/pull/129

`lockdown_status` in `worldmap.json`

Example:
```
"features": [{
    "type": "Feature",
    "properties": {
      "iso2": "AF",
      "iso3": "AFG",
      "NAME": "Afghanistan",
      "lockdown_status": "3"
    },
}]
```

### CODE REVIEW

**Comment by thepassle** [comment]
Nice work ilyas 😄 

I see ssome values are a Number and some are a String, is this intentional?

```json
{
   "lockdown":{
      "title_of_status":null,
      "entry_date":"3 April 2020",
      "measures":[
         {
            "label":"max_gathering",
            "value":3
         },
         {
            "label":"lockdown_status",
            "value":"3"
         },
         {
            "label":"city_movement_restriction",
            "value":"3"
         },
      ]
   }
}
```

**Comment by ilyasfoo** [comment]
> Nice work ilyas 😄
> 
> I see ssome values are a Number and some are a String, is this intentional?

Yes it was an issue, there was a data fix [here](https://github.com/Code-for-All/lockdown/pull/130/commits/362bf6f010196c3c409916c95917a1354abd46a1). 

It should look like this now:
```json
{
  "lockdown": {
    "title_of_status": "State of Neglect",
    "entry_date": "3 April 2020",
    "measures": [{
      "label": "max_gathering",
      "value": 3
    }, {
      "label": "lockdown_status",
      "value": "3"
    }, {
      "label": "city_movement_restriction",
      "value": "3"
    }]
  }
}
```

> In some I see the value `5`, i thought there were only 3 options?
> 
> ```json
>             {
>                "label":"stopovers",
>                "value":null
>             },
>             {
>                "label":"commerce",
>                "value":"5"
>             }
> ```

According to the new definition, there's now 5:
```javascript
const TRAVEL = {
  YES: '1',
  PARTIALLY: '2',
  NO: '3',
  UNCLEAR: '4',
  NA: '5',
};
```

I've put all definitions in [shared/types.js](https://github.com/ilyasfoo/lockdown/blob/9eaef2dfe8dd2bfeeb05700ff7107cdcf127bf79/shared/types.js#L42-L49
)

**Comment by thepassle** [comment]
Alright cool, I see

One more small thing:

I see that the `lockdown.travel.flight` has an extra entry: `stopovers`, which is `null`, this should also have a value (1-5) right? 

```json
            {
               "label":"stopovers",
               "value":null
            },
```

**Comment by thepassle** [comment]
Did some more digging into this, it seems like `flight` has a `stopovers` field, that `sea` and `land` _dont_ have

and

`sea` and `land` have a `cross_border_workers` field that `flight` does _not_ have. 

Example:

```diff
"flight":[
           {
              "label":"local",
              "value":"3"
           },
           {
              "label":"nationals_inbound",
              "value":"2"
           },
           {
              "label":"nationals_outbound",
              "value":"3"
           },
           {
              "label":"foreigners_inbound",
              "value":"3"
           },
           {
              "label":"foreigners_outbound",
              "value":"1"
           },
+          {
+             "label":"stopovers",
+             "value":"1"
+          },
           {
              "label":"commerce",
              "value":"5"
           }
        ],
```

Land/sea:

```diff
"sea/land":[
           {
              "label":"local",
              "value":"3"
           },
           {
              "label":"nationals_inbound",
              "value":"2"
           },
           {
              "label":"nationals_outbound",
              "value":"3"
           },
           {
              "label":"foreigners_inbound",
              "value":"3"
           },
           {
              "label":"foreigners_outbound",
              "value":"1"
           },
+          {
+             "label":"cross_border_workers",
+             "value":"3"
+          },
           {
              "label":"commerce",
              "value":"1"
           }
        ]
```

Could we make it like this instead? So for the `flight` example, we add the `cross_border_workers` field, but just give it the NA applicable value (`5`)

```diff
"flight":[
           {
              "label":"local",
              "value":"3"
           },
           {
              "label":"nationals_inbound",
              "value":"2"
           },
           {
              "label":"nationals_outbound",
              "value":"3"
           },
           {
              "label":"foreigners_inbound",
              "value":"3"
           },
           {
              "label":"foreigners_outbound",
              "value":"1"
           },
+          {
+             "label":"stopovers",
+             "value":"1"
+          },
           {
              "label":"commerce",
              "value":"5"
           },
+         {
+           "label":"cross_border_workers",
+           "value":"5"
+          },
        ],
```

And sea/land:

```diff
      "sea/land":[
           {
              "label":"local",
              "value":"3"
           },
           {
              "label":"nationals_inbound",
              "value":"2"
           },
           {
              "label":"nationals_outbound",
              "value":"3"
           },
           {
              "label":"foreigners_inbound",
              "value":"3"
           },
           {
              "label":"foreigners_outbound",
              "value":"1"
           },
+          {
+             "label":"cross_border_workers",
+             "value":"3"
+          },
           {
              "label":"commerce",
              "value":"1"
           },
+          {
+            "label":"stopovers",
+            "value":"5"
+          }
        ]
```

## Point 2:
As I understand correctly the max gathering field is the actual number of people allowed together, and does not correspond to an ENUM, correct?

If so, that's fine, but the designs don't reflect this, so I'll contact the UX group about this.

These are my final comments, I promise 😛  Again, really nice work!

**Comment by ilyasfoo** [comment]
> I see that the `lockdown.travel.flight` has an extra entry: `stopovers`, which is `null`, this should also have a value (1-5) right?

The `null` value actually signifies that the data is empty/invalid coming from google sheet. I am reluctant to provide a default value as the absence of value sometimes has its own interpretation. However, if you do feel frontend will behave the same, I think `UNCLEAR` (4) might be the closest one. Let me know and I'll set it as default @thepassle .

> Could we make it like this instead? So for the flight example, we add the cross_border_workers field, but just give it the NA applicable value (5)

Understood your point, will get into it

> As I understand correctly the max gathering field is the actual number of people allowed together, and does not correspond to an ENUM, correct?
> If so, that's fine, but the designs don't reflect this, so I'll contact the UX group about this.

Yes

> Since max_gatherings is denoted as an actual number, and not an icon, could we move it up and outside of the measures field? e.g.:

Can

**Comment by ilyasfoo** [comment]
@thepassle I've updated, please have a look

```json
{
  "lockdown": {
    "title_of_status": "State of Neglect",
    "entry_date": "4 April 2020",
    "max_gathering": 50,
    "measures": [{
      "label": "lockdown_status",
      "value": "1"
    }, {
      "label": "city_movement_restriction",
      "value": "2"
    }, {
      "label": "attending_religious_sites",
      "value": "1"
    }, {
      "label": "going_to_work",
      "value": "1"
    }, {
      "label": "military_not_deployed",
      "value": "1"
    }, {
      "label": "academia_allowed",
      "value": "2"
    }, {
      "label": "going_to_shops",
      "value": "2"
    }, {
      "label": "electricity_nominal",
      "value": "1"
    }, {
      "label": "water_nominal",
      "value": "1"
    }, {
      "label": "internet_nominal",
      "value": "3"
    }],
    "travel": {
      "land": [{
        "label": "local",
        "value": "2"
      }, {
        "label": "nationals_inbound",
        "value": "2"
      }, {
        "label": "nationals_outbound",
        "value": "3"
      }, {
        "label": "foreigners_inbound",
        "value": "3"
      }, {
        "label": "foreigners_outbound",
        "value": "1"
      }, {
        "label": "cross_border_workers",
        "value": "3"
      }, {
        "label": "stopovers",
        "value": "5"
      }, {
        "label": "commerce",
        "value": "2"
      }],
      "flight": [{
        "label": "local",
        "value": "2"
      }, {
        "label": "nationals_inbound",
        "value": "2"
      }, {
        "label": "nationals_outbound",
        "value": "3"
      }, {
        "label": "foreigners_inbound",
        "value": "3"
      }, {
        "label": "foreigners_outbound",
        "value": "1"
      }, {
        "label": "cross_border_workers",
        "value": "5"
      }, {
        "label": "stopovers",
        "value": null
      }, {
        "label": "commerce",
        "value": "5"
      }],
      "sea": [{
        "label": "local",
        "value": "2"
      }, {
        "label": "nationals_inbound",
        "value": "2"
      }, {
        "label": "nationals_outbound",
        "value": "3"
      }, {
        "label": "foreigners_inbound",
        "value": "3"
      }, {
        "label": "foreigners_outbound",
        "value": "1"
      }, {
        "label": "cross_border_workers",
        "value": "2"
      }, {
        "label": "stopovers",
        "value": "5"
      }, {
        "label": "commerce",
        "value": "1"
      }]
    }
  }
}
```

**Comment by thepassle** [comment]
Yep, that looks great. Thats pretty much all I need for #131 

> The null value actually signifies that the data is empty/invalid coming from google sheet. I am reluctant to provide a default value as the absence of value sometimes has its own interpretation. However, if you do feel frontend will behave the same, I think UNCLEAR (4) might be the closest one. Let me know and I'll set it as default @thepassle .

Could you help me understand this more? Which interpretations can the absence of a value have? From my (or a users) perspective, if we dont have any data, we should show a grey icon which corresponds to NA (5).

**Comment by LarsDenBakker** [comment]
If a property is optional, I'd prefer to leave it out so that the JSON is smaller. (it will be undefined in JS then). If a property is required, we need to throw an error otherwise we will get strange results in the front-end.

**Comment by thepassle** [comment]
> If a property is optional, I'd prefer to leave it out so that the JSON is smaller. (it will be undefined in JS then). If a property is required, we need to throw an error otherwise we will get strange results in the front-end.

Then we will have to throw things around again... In the frontend currently I do a mapping which basically makes this of it:

`land: ["4", "2",  "2"]`

so we can render the status:
image

But this depends on the data/fields to be consistent and the same

**Comment by LarsDenBakker** [comment]
Why does that require moving around? In your example they all have defined values.

**Comment by thepassle** [comment]
> Why does that require moving around? In your example they all have defined values.

Thats exactly the point, there are 3 (land, sea, flight) arrays that I loop over. If flight has a property that sea/land doesnt have, the output will not correspond to the correct measure. E.g.:

```js
{
  land: [{label:"foo", value:"foo1"}, {label:"bar", value:"bar2"}]
  sea: [{label:"baz", value:"baz1"}, {label:"boo", value:"boo2"}]
}
```

Output:

`foo: ["foo1", "baz1"]`

expected:
`foo: ["foo1", "foo1|2|3|4|5"]`

**Comment by LarsDenBakker** [comment]
I see see your point, those would need to be required properties then. The value can be null or an extra enum value.

**Comment by LarsDenBakker** [comment]
How can we ensure all the data structures are always in sync with each other? Do we have defined anywhere what the possible values are?

**Comment by thepassle** [comment]
By just adhering to this schema: https://github.com/Code-for-All/lockdown/pull/130#issuecomment-608923081

**Comment by ilyasfoo** [comment]
> Could you help me understand this more? Which interpretations can the absence of a value have? From my (or a users) perspective, if we dont have any data, we should show a grey icon which corresponds to NA (5).

Alright then that settles it, will set the default to NA.

**Comment by ilyasfoo** [comment]
> Could you help me understand this more? Which interpretations can the absence of a value have? From my (or a users) perspective, if we dont have any data, we should show a grey icon which corresponds to NA (5).

Actually this was referring to sheet cells that was *supposed* to have a value, but was empty, thus script was returning `nulls`. But then I think sheet definition has changed (stopovers now looks strikedout). Will ask Jean again on this, but my intention was if sheet cell was not filled, it should either return `null` or `Unclear` (4). If stopovers confirmed to be removed from sheet, we might as well remove them.

image

Wait, this is for sheets that have the field, but the cell is empty. NA I believe refers to `Not Applicable`, while

**Comment by thepassle** [comment]
@JFQueralt ?

**Comment by ilyasfoo** [comment]
@thepassle there will be some changes to scripts, now the direction is to build in business logic. Will update as it goes along. No changes to the final JSON output though

**Comment by thepassle** [comment]
@ilyasfoo Okay, looking forward, keep me posted 🙂

**Comment by ilyasfoo** [comment]
Sorry, closing as everything is bundled together into https://github.com/Code-for-All/lockdown/pull/137

**Pull request closed without merging**
