### PR TITLE
Improve contrast for country and state labels and border lines

### PR DESCRIPTION
**Pull request by planemad**
- Move 'admin-0-fill' layer before the 'admin-1-boundary-bg' boundary line layers
- Add runtime map style improvements for improved contrast of:
  - Country and state labels
  - Country and state lines
- Make water white for improved contrast with land
- Fix implementation of default color for no values or undefined lockdown values
- Create a variable `selectedWorldview` to easily control the boundary version for disputed areas in future. Ref: https://docs.mapbox.com/vector-tiles/reference/mapbox-boundaries-v3/#--polygon---worldview-text
  

Before

Screen Shot 2020-05-13 at 7 37 03 PM

After

Screen Shot 2020-05-13 at 7 37 22 PM

cc @aherreDev @JFQueralt

### CODE REVIEW

**Comment by planemad** [comment]
If we want to support dark mode on the map, the simplest way would be to change the color of water from white to something dark

`map.setPaintProperty('water','fill-color','#444');`

Screen Shot 2020-05-13 at 7 48 59 PM

**Comment by planemad** [comment]
Another enhancement:
- Added map hash to the url so that links can be share to a particular map view

Screen Shot 2020-05-13 at 8 10 48 PM

**Comment by planemad** [comment]
For future reference:
- Since i dont have access to the actual style used in `jfqueralt` Mapbox account, i created a new monochrome light style in Mapbox Studio to get a sense of the layers available for styling. Alternatively one can also get this by using `map.getStyle().layers`  in the web dev JS console.
- Tried out different colors values on the test map in Mapbox Studio to get a sense of how the end result would look.
- Implemented the style change of the specific layers using https://docs.mapbox.com/mapbox-gl-js/api/#map#setpaintproperty and https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/

**Comment by planemad** [comment]
Made water color grey based on feedback

Screen Shot 2020-05-14 at 3 02 30 PM

Screen Shot 2020-05-14 at 2 56 47 PM

**Comment by planemad** [comment]
Use palette color '#e0e0e0' for the water.

Screen Shot 2020-05-14 at 10 50 52 PM

cc @petrajaaskelainen

**Comment by petrajaaskelainen** [comment]
If you want to use the different color for the water on dark mode, you can use #4F4F4F - it is currently the darkest shade after #333 in our visual identity design

**Comment by planemad** [comment]
> If you want to use the different color for the water on dark mode, you can use #4F4F4F - it is currently the darkest shade after #333 in our visual identity design

@petrajaaskelainen this PR does not implement any changes for dark mode, that would touch a different part of the code which triggers the dark mode and is best implemented seperately.

**Comment by petrajaaskelainen** [comment]
Ah, ok! I just saw the comment above regarding it so commented on that - but so you know :)

**Comment by aherreDev** [comment]
Let's do the merge

**Pull request merged**
